apiVersion: v1
kind: ConfigMap
metadata:
  name: smartlive-config
  namespace: smartlive
data:
  OLLAMA_BASE_URL: http://ollama:11434
  OLLAMA_MODEL: llama3.1
  OLLAMA_TIMEOUT_SECONDS: "3"
  DATABASE_URL: postgresql://smartlive:smartlive@postgres:5432/smartlive
  AI_TEMPERATURE: "0.2"
  AI_MAX_TOKENS: "220"
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  AUTH_SERVICE_URL: http://auth-service:8010
  USER_SERVICE_URL: http://user-service:8011
  SHOP_SERVICE_URL: http://shop-service:8012
  PRODUCT_SERVICE_URL: http://product-service:8013
  VOUCHER_SERVICE_URL: http://voucher-service:8014
  LIVESTREAM_SERVICE_URL: http://livestream-service:8015
  CHAT_SERVICE_URL: http://chat-service:8016
  AI_SERVICE_URL: http://ai-assistant-service:8001
  ORDER_SERVICE_URL: http://order-service:8017
  NOTIFICATION_SERVICE_URL: http://notification-service:8018
  ANALYTICS_SERVICE_URL: http://analytics-service:8019
  REDIS_URL: redis://redis:6379/0
