apiVersion: v1
kind: Secret
metadata:
  name: smartlive-secret
  namespace: smartlive
type: Opaque
stringData:
  JWT_SECRET: change-me
  POSTGRES_PASSWORD: smartlive
  MINIO_ROOT_PASSWORD: smartlive123
